name: Create QubesOS RPMs

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  grub2:
    uses: zarhus/qubes-builder-workflows/.github/workflows/qubes-dom0-packagev2.yml@sq
    with:
      qubes-component: 'grub2'
    secrets: inherit
